# Site settings
title: Greg's Blog
email: Greg.Samek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Science | Technology | Engineering | Art | Mathematics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samek.io" # the base hostname & protocol for your site
twitter_username: gregsamek
github_username:  gregsamek

# Build settings
markdown: kramdown

# Posts per page
paginate: 50