# Site settings
title: SAMEK.IO
email: greg@samek.io
description: > # this means to ignore newlines until "baseurl:"
  Science | Tech | Engineering | Art | Math
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samek.io" # the base hostname & protocol for your site
twitter_username: gregsamek
github_username:  gregsamek

# Build settings
markdown: kramdown

# Posts per page
paginate: 5
paginate_path: "/blog/page:num/"